# Note: You must restart bin/webpacker-dev-server for changes to take effect

default: &default
  source_path: ./**/app/packs/
  source_entry_path: entrypoints
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  # additional_paths: []
  additional_paths:
    - ../node_modules
    - ../../components/multimedia/app/packs/entrypoints/multimedia
    - ../components/multimedia/app/packs/entrypoints/multimedia
    - ../../components/room/app/packs/elm
    - ../components/room/app/packs/elm

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Check for consistent versions of shakapacker gem and npm package
  ensure_consistent_versioning: true

development:
  <<: *default
  compile: true
  cache_manifest: false

  dev_server:
    https: false
    host: localhost
    port: 8080
    hmr: true
    inline: true
    client:
      overlay: true
    compress: true
    allowed_hosts: "all"
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
